project:
  type: website

website:
  title: "dylanmhughes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - about.qmd

format:
  html:
    theme: Journal
    css: styles.css
    toc: true

editor: visual

