project:
  type: website

website:
  title: "Dylan Hughes"
  page-footer: |
    Made with [Quarto](https://quarto.org/)
  navbar:
    left:
      - href: about.qmd
        text: ABOUT
      - href: now.qmd
        text: NOW
      - href: projects.qmd
        text: PROJECTS
    right:
      - icon: github
        href: https://github.com/dmhhughes
      - icon: linkedin
        href: https://linkedin.com/in/dylan-m-h-hughes
      - icon: envelope
        href: mailto:dylanhughes9@live.com

format:
  html:
    theme: 
        - mystyles.scss
    toc: true
    link-external-newwindow: true

