---
title: "A Little About Me"
---

I'm a data professional working for [Farm Credit Services of America](https:///www.fcsamerica.com/). I live in [Fargo, North Dakota](https://www.fargomoorhead.org/) with my soon-to-be wife and our goldendoodle, Ellie. I enjoy coffee, taking our dog for walks, working out, and listening to podcasts.

I attended the [University of North Dakota](https://und.edu/about/index.html) and obtained a [Bachelors of Accountancy](https://und.edu/programs/accountancy-bacc/requirements.html) and a [Bachelors of Business Adminstration](https://und.edu/programs/business-economics-bba/requirements.html), specializing in Economics.

I began my professional life in finance before finding a career in data. These days, I work primarily with open-source technologies. I prefer to program using the [R programming language](https://cran.r-project.org/) and use [Quarto](https://quarto.org/) as my means of communication.

I have extensive analytics experience, having developed an enterprise reporting framework from scratch, creating a Center of Excellence to expand the impact of analytics, and building a loan decision engine which handles over $3 billion in loan commitments annually.